-- --------------------------------------------------------
-- Strežnik:                     127.0.0.1
-- Verzija strežnika:            10.2.13-MariaDB - mariadb.org binary distribution
-- Operacijski sistem strežnika: Win64
-- HeidiSQL Različica:           9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for sunt
CREATE DATABASE IF NOT EXISTS `sunt` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_slovenian_ci */;
USE `sunt`;

-- Dumping structure for tabela sunt.author
CREATE TABLE IF NOT EXISTS `author` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `biography` varchar(1023) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_biography` varchar(1023) COLLATE utf8_slovenian_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.author: 26 rows
/*!40000 ALTER TABLE `author` DISABLE KEYS */;
INSERT INTO `author` (`id`, `name`, `biography`, `english_biography`) VALUES
	(1, 'Maja Smrekar', 'Maja SMREKAR (1978, Brežice)\nDiplomirala na Akademiji za likovno umetnost in oblikovanje v Ljubljani pri prof. Jožetu Baršiju, smer kiparstvo, in pri somentorju prof. dr. Jožefu Muhoviču ter somentorici prof. Meti Hočevar  (2006), kjer je na  Oddelku za video in nove medije zaključila magistrski študij pri prof. Srečku Draganu (2016).\n', 'Maja Smrekar (1978, Brežice)\nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Jože Barši and co-mentor prof. dr. Jože Muhovič and prof. Meta Hočevar (2006), where she finished Master\'s Degree in Video and New Media under prof. Srečo Dragan (2016).'),
	(2, 'Marko Glavač', 'Marko GLAVAČ (1959, Ljubljana) Diplomiral na Akademiji za likovno umetnost in oblikovanje pri prof. Alenu Ožboltu, smer kiparstvo, in likovna teorija pri prof. dr Jožefu Muhoviču in prof. dr. Tomaž Brejc (2007), kjer je zaključil tudi magistrski študij pri prof. Sreču Draganu, smer video in novi mediji  (2010).', 'Marko Glavač (1959, Ljubljana) Graduated from the Academy of Fine Arts and Design under prof. Len Ožbolt in Sculpture and Art Theory under prof. Jože Muhovič and prof. dr. Tomaž Brejc (2007), where he finished Master\'s degree under prof. Srečo Dragan in Video and New Media (2010).'),
	(3, 'Narvika Bovcon in Aleš Vaupotič', 'Narvika Bovcon\nDiplomirala na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Ranku Novaku, prof. Zdravku Papiču in prof. dr. Stanetu Berniku, smer vizualne komunikacije  (2001), kjer je zaključila tudi magistrski študij videa in novih medijev pri prof. Sreču Draganu (2003) in doktorirala iz teorije novih medijev  pri prof. dr. Stanetu Berniku, prof. dr. Janezu Strehovcu in prof. Sreču Draganu (2008). \nAleš Vaupotič \nDiplomiral na Filozofski fakulteti v Ljubljani, pri prof. dr. Tomu Virku in prof. dr. Ladu Kralju, iz primerjalne književnosti in literarne teorije(2001). Magistrski študij videa in novih medijev zaključil na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Sreču Draganu (2004). Doktoriral iz literarne vede na Filozofski fakulteti v Ljubljani, pri prof. dr. Tomu Virku, prof. dr. Janezu Strehovcu in prof. Sreču Draganu (2011).\n', 'Narvika Bovcon\nGraduated from the Academy of Fine Arts and Design in Ljubljana, under prof. Ranko Novak, prof. Zdravko Papič and prof. dr. Stane Bernik in Visual Communications (2001), where she also finished Master\'s degree in Video and New Media under prof. Srečo Dragan (2003) and finished her Doctoral degree in Theory of New Media under prof. dr. Stane Bernik, prof. dr. Janez Strehovc and prof. Srečo Dragan (2003).\nAleš Vaupotič\nGraduated from the Faculty of Philosophy in Ljubljana under prof. dr. Tomo Virk and prof. dr. Lado Dralj in Comparative Literature and Literal Theory (2001). He finished Master\'s degree in Video and New Media at the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan (2004). He received Doctoral degree in Literal Science at the Faculty of Philosophy in Ljubljana under prof. dr. Tomo Virk, prof. dr. Janez Strehovc and prof. Srečo Dragan (2011).'),
	(4, 'Franc Solina', 'Franc SOLINA (1955, Celje)\nDiplomiral iz elektrotehnike na Univerzi v Ljubljani  (1979) in doktoriral iz računalništva na University of Pennsylvania v Filadelfiji  (1987). Likovno se je izpopolnjeval med dvajsetletnim sodelovanjem s prof. Srečom Draganom pri produkciji novomedijske umetnosti in v kiparskih delavnicah pod mentorstvom akad. kip. Alenke Vidrgar.\n', 'Franc Solina (1955, Celje)\nGraduated from the Faculty of Electrical Engineering in Ljubljana (1979) and got Doctoral degree in Computer Science at the University of Pennsylvania in Philadephia (1987). He was introduced to fine arts during his work with prof. Srečo Dragan on production of new-media art and during sculptural lectures under mentorship of acad. sculptor Alenka Vidrgar.\n'),
	(5, 'Matija Jašarov', 'Matija JAŠAROV (1983, Celje)\nDiplomiral iz glasbene produkcije na Academy of Contemporary Music, Guildford, Združeno Kraljestvo (2006). Magistrski študij videa in novih medijev zaključil na Akademiji za likovno umetnost in oblikovanje pri prof. Sreču Draganu (2016).\n', 'Mitja Jašarov (1983, Celje) \nGraduated in musical production from the Academy of Contemporary Music, Guildford, UK (2006). He finished Master\'s degree in Video and New Media at the Academy of Fine Arts and Design in Ljubljana under prof.Srečo Dragan (2016).\n'),
	(6, 'Zoran Poznič, Maja Jazbec in Andrej Uduč', 'Maša Jazbec (1981, Trbovlje) Diplomirala na Univerzi v Mariboru, smer likovna pedagogika, pri prof. Dušanu Zidarju. Zaključila magistrski študij iz novih medijev na Univerzi v Linzu pri prof. Christi Sommerer. Trenutno doktorska kandidatka na Univerzi v Tsukubi na Japonskem pri prof. Hiroo Iwata. \nZoran Poznič (1959, Trbovlje) Diplomiral na ALUO v Ljubljani pri profesorju Alenu Ožboltu, smer kiparstvo, kjer je tudi magistriral iz videa in novih medijev pri prof. Sreču Draganu.\nAndrej Uduč (1979, Kranj) Diplomiral na Fakulteti za družbene vede Univerze v Ljubljani iz sociologije – analitsko teoretska smer.', 'Maša Jazbec (1981, Trbovlje) \nGraduated from the University of Maribor in Art Education under prof. Dušan Zidar. She finished her Master\'s degree in New Media at the University of Linz under prof. Christi Sommerer. She is currently Doctoral degree candidate at the University of Tsukuba in Japan under prof. Hiroo Iwata.\nZoran Poznič (1959, Trbovlje)\nGraduated from the Academy of Fine Arts and Design under prof. Alen Ožbolt, where he also got his Master\'s degree in Video and New Media under prof. Srečo Dragan.\nAndrej Uduč (1979, Kranj) \nGraduated from the Faculty of Social Sciences in sociology - analytical theoretical direction.\n'),
	(7, 'Tilen Žbona', 'Tilen ŽBONA (1976, Koper)\nDiplomiral na Akademiji lepih umetnosti v Benetkah (Accademia di Belle Arti di Venezia), smer slikarstvo, pri profesorju Carlu Di Raci (2001). Magistrski študij je zaključil na Akademiji likovne umetnosti na Univerzi v Ljubljani pri prof. Sreču Draganu  (2007). Doktoriral s področja likovne didaktike, smer izobraževanje učiteljev in edukacijske vede na Pedagoški Fakulteti Univerze v Ljubljani, pri izr. prof. dr.  Beatriz Gabrieli Tomšič Čerkez in prof. dr. Francu Solini (2017).\n', 'Tilen Žbona (1976, Koper) \nGraduated from the Academia di Belle Arti in Venice under prof. Carlo Di Raci (2001). He finished his Master\'s degree at the Academy of Fine Arts and Design of the University of Ljubljana under prof. Srečo Dragan (2007). He got Doctoral degree in Artistic Didactics at the Faculty of Education of University of Ljubljana under prof. Beatriz Gabriela Tomžiš Čerkez and prof. dr. Franc Solina (2017).\n'),
	(8, 'Peter Ciuha', 'Peter CIUHA (1968, Ljubljana)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Janezu Berniku, smer slikarstvo in pri prof. dr. Jožefu Muhoviču, smer likovna teorija  (1992), kjer je zaključil tudi magistrski študij grafike zaključil  pri prof. Lojzetu Logarju(2001)  in magistrski študij videa  pri prof. Sreču Draganu (2016).\n', 'Peter Ciuha (1968, Ljubljana) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Janez Bernik and prof. dr. Jože Muhovič (1992), where he also finished Master\'s degree in Graphics under prof. Lojze Logar (2001) and Master\'s degree in Video under prof. Srečo Dragan (2016). \n'),
	(9, 'Miran Kreš', 'Miran KREŠ (1973, Ljubljana)\nDiplomiral na Akademiji za likovno umetnost v Ljubljani, smer slikarstvo pri prof. Zdenku Huzjanu (1998). in prof. dr. Janezu Strehovcu (2000), kjer je nadaljeval magistrski študij videa in novih medijev na katedri za video ALUO Ljubljana pri prof. Sreču Draganu in na FF v Ljubljani pri prof. dr. Jožetu Vogrincu zaključil teorijo množičnih medijev (2011).', 'Miran Kreš (1973, Ljubljana) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Zdenko Huzjan (1998) and prof. dr. Janez Strehovec (2000), where he continued with Master\'s degree in Video and New Media at the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan and at the Faculty of Philosophy in Ljubljana under prof. dr. Jože Vogrinc, where he finished the Theory of Mass Media (2011).\n'),
	(10, 'Evelin Stermitz', 'Evelin STERMITZ (1972, Avstrija)\nŠtudij pedagogike in medijskih komunikacij je zaključila na Univerzi v Celovcu (1999) in ga nadaljevala na Akademiji za likovno umetnost in oblikovanje v Ljubljani, smer video in novi mediji pri prof. Sreču Draganu in smer fotografija pri prof. Milanu Pajku (2007).\n', 'Evelin Stermitz (1972, Avstrija) \nFinished her study in Education and Media Communication at the University of Klagenfurt (1999) and the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan and prof. Milan Pajk (2007).\n'),
	(11, 'Gorazd Krnc', 'Gorazd KRNC (1973, Ljubljana)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani pri prof. Gustavu Gnamušu, smer slikarstvo, in pri prof. Sreču Draganu, smer video (1998), kjer je pri istem profesorju zaključil magistrski študij videa in novih medijev (2007).\n', 'Gorazd Krnc (1973, Ljubljana) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Gustav Gnamuš and under prof. Srečo Dragan (1998), where he finished Master\'s degree in Video and New Media under the same professor (2007).\n'),
	(12, 'Metka Zupanič', 'Metka ZUPANIČ (1977, Ptuj)\nDiplomirala na Akademiji za likovno umetnost in oblikovanje pri prof. Luju Vodopivcu, smer kiparstvo(2002). Istega leta študij nadaljevala na podiplomskem študiju videa in novih medijev ter leta 2005 magistrirala pod mentorstvom prof. Sreča Dragana.\n', 'Metka Zupanič (1977, Ptuj) \nGraduated from the Academy of Fine Arts and Design under prof. Lu Vodopivc (2002). She continued postgraduate studies in Video and New Media and in 2005 got her Master\'s degree under mentorship of prof. Srečo Dragan.\n'),
	(13, 'Artur Felicijan in Andraž Sedmak', 'Artur Felicijan (1983, Ljubljana) Diplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Sreču Draganu, smer video (2008), pri istem profesorju zaključil magistrski študij videa (2016).\nAndraž Sedmak (1984, Koper) Diplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Sreču Draganu, smer video (2008), pri istem profesorju zaključil magistrski študij videa (2016).', 'Artur Felicijan (1983, Ljubljana) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan in Video (2008) and got Master\'s degree in Video in 2016 under the same professor.\nAndraž Sedmak (1984, Koper) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Sre?o Dragan and got Master\'s degree under the same professor in 2016.\n'),
	(14, 'Robert Černelč', 'Robert ČERNELČ (1970, Murska Sobota)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani, pri prof. Emeriku Bernardu, smer slikarstvo in pri prof. Sreču Draganu, smer video (1999), kjer je zaključil tudi  magistrski študij slikarstva  pri prof. Hermanu Gvardjančiču  (2002).  Magistrski študij filmske režije zaključil na Akademiji za gledališče, radio, film in televizijo, pri prof. Miranu Zupaniču (2004).', 'Robert Černelč (1970, Murska Sobota)\nGraduated from Academy of Fine Arts and Design in Ljubljana under prof. Emerik Bernard and under prof. Srečo Dragan (1999), where he also finished his Master\'s degree in Painting under prof. Herman Gvardjančič (2002). He finished his Master\'s degree in Film Directing at the Academy of Theatre, Radio, Film and Televison under prof. Miran Zupanič (2004). \n'),
	(15, 'Dominik Križan', 'Dominik KRIŽAN OLMIAH (1968, Jesenice)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani pri prof. Emeriku Bernardu, smer slikarstvo, in pri  prof. Sreču Draganu, smer z video in novi mediji;  risba pri prof. Janezu Berniku; sociologija kulture pri prof. Alešu Debeljaku  (1996). Na  isti akademiji zaključil magistrski študij grafike pri prof. Lojzetu Logarju. Sreču Draganu in prof. dr. Janezu Strehovcu  (2000). Magistrski študij videa in novih medijev zaključil na katedri za video ALUO Ljubljana pri prof. Sreču Draganu ter pri  prof.dr. Jožetu Vogrincu študij teorije množičnih medijev na  FF Ljubljana (2011).\n', 'Dominik Križan Olmiah (1968, Jesenice) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Emerik Bernard and prof. Srečo Dragan in Video and New Media. At the same Academy he finished his Master\'s degree in Graphics under prof. Lojze Logar, prof. Srečo Dragan and prof. dr. Janez Strehovec.\n'),
	(16, 'Aleš Sedmak', 'Aleš SEDMAK (1952, Postojna)\nDiplomiral na Akademiji za likovno umetnost v Ljubljani, smer slikarstvo pri prof. Janezu Berniku in prof. Andreju Jemcu (1980).\n', 'Aleš Sedmak (1952, Postojna) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Janez Bernik and prof. Andrej Jemec (1980).\n'),
	(17, 'Črtomir Frelih', 'Črtomir FRELIH (1960, Nomenj)\nDiplomiral na Akademiji za likovno umetnost v Ljubljani pri prof. Zvestu Apolloniju, smer grafika (1985), kjer je zaključil tudi specialistični študij grafike  pri prof. Zvestu Apolloniju in prof. Branku Suhyju(1990) ter magisterij znanosti s področja likovne didaktike (1997).\n', 'Črtomir Frelih (1960, Nomenj) \nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Zvest Apolloni (1985), where he also finished his specialist Graphics Studies under prof. Zvest Apolloni and prof. Branko Suhy (1990) and the Master of Science of Artistic Didactics (1997).\n'),
	(18, 'Dorian Španzel', 'Dorian Rudolf ŠPANZEL (1984, Ljubljana)\nDiplomiral iz oblikovanja in sodobne umetnosti na Accademia di Belle Arti v Benetkah. Magistrski študij videa in novih medijev zaključil na ALUO, Ljubljana, pri prof. Sreču Draganu(2012).\n', 'Dorian Rudolf Španzel (1984, Ljubljana) \nGraduated from Design and Contemporary Art from Academia di Belle Arti in Venice. He finished his Master\'s degree in Video and New Media at the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan (2012).\n'),
	(19, 'Duša Jesih', 'Duša JESIH (1977, Ljubljana)\nDiplomirala na Šoli za risanje in slikanje, smer slikarstvo (2003), kjer je končala tudi podiplomski študij slikarstva pri prof. Zmagu Lenardiču (2006).  Magistrski študij zaključila na Akademiji za likovno umetnost in oblikovanje v Ljubljani pri prof. Zmagu Lenardiču, smer slikarstvo, in pri prof. Sergeju Kapusu, smer oblikovne zasnove (2015).\n', 'Duša Jesih (1977, Ljubljana) \nGraduated at the  School of Drawing and Painting, where she finished her postgraduate study of painting under prof. Zmago Lenardi? (2006). She finished her Master\'s degree from the Academy of Fine Arts and Design in Ljubljana under prof. Zmago Lenardič and prof. Sergej Kapus (2015).\n'),
	(20, 'Zoran Srdić Janežič', 'Zoran SRDIĆ JANEŽIČ (1974, Kranj)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje v Ljubljani, smer kiparstvo, pri prof. Sreču Draganu (2004).\n', 'Zoran Srdić Janežič (1974, Kranj)\nGraduated from Academy of Fine Arts and Design in Ljubljana in Sculpture under prof. Srečo Dragan (2004).\n'),
	(21, 'Peter Marolt', 'Peter MAROLT (1965,  Ljubljana)\nDiplomiral na tedanji Šoli za arhitekturo, FAGG v Ljubljani, smer oblikovanje  (1993). Leta 2001 pridobil znanstveni magisterij iz področja arhitekture in s temo Pomen likovnosti za arhitekturni prostor, na isti ustanovi –  Fakulteti za arhitekturo, Univerze v Ljubljani, tudi doktoriral (2004).\n', 'Peter Marolt (1965, Ljubljana) \nGraduated from the School of Architecture, FAGG in Ljubljana (1993). In 2001 he acquired his Master of Science in Architecture with a thesis »The importance of art in the architectural space« and finished his Doctoral degree in 2004 at the same institution.\n'),
	(22, 'Tomaž Furlan', 'Tomaž FURLAN (1960, Nomenj)\nDiplomiral na Akademiji za likovno umestnost in oblikovanje v Ljubljani, pri prof. Jožetu Baršiju in prof. Borutu Vogelniku, smer kiparstvo (2016).\n', 'Tomaž Furlan (1960, Nomenj)\nGraduated from the Academy of Fine Arts and Design in Ljubljana under prof. Jože Barši and prof. Borut Vogelnik (2016).\n'),
	(23, 'Vesna Čadež', 'Vesna ČADEŽ (1976, Ljubljana)\nDiplomirala na Akademiji za likovno umetnost in oblikovanje v Ljubljani (2004), kjer je zaključila tudi magistrski študij slikarstva pri prof. Metki Krašovec in videa pri prof. Sreču Draganu  (2008).\n', 'Vesna Čadež (1976, Ljubljana) \nGraduated from the Academy of Fine Arts and Design in Ljubljana (2004), where she also finished her Master\'s degree in painting under prof. Metka Krašovec and prof. Srečo Dragan (2008).\n'),
	(24, 'Vanja Mervič', 'Vanja MERVIČ (1973, Koper)\nDiplomiral na Accademia di Brera v Milanu, Italija, pri prof. Nicoli Salvatoreju, smer slikarstvo, in pri prof. Francescu Ballu, smer metode in teorija multimedije (2001). Magistrski študij videa in novih medijev zaključil na ALUO, Ljubljana, pri prof. Sreču Draganu (2008).\n', 'Vanja Mervič (1973, Koper) \nGraduated from the Accademia di Brera in Milan, Italy under prof. Nicoli Salvatore and prof. Francesco Ballo in Video and Methods and Theory of Multimedia (2001). He finished his Master\'s degree in Video and New Media at the Academy of Fine Arts and Design in Ljubljana under prof. Srečo Dragan (2008).\n'),
	(25, 'Jure Fingušt Prebil', 'Jure FINGUŠT PREBIL (1989, Ljubljana)\nDiplomiral na Akademiji za likovno umetnost in oblikovanje, pri prof. Sreču Draganu, smer kiparstvo (2012). Magistrski študij zaključil na Universität für Künstlerische und Industrielle Gestaltung Linz, Avstrija, smer Interface Cultures pri prof. Dr. Christi Sommerer (2017).\n', 'Jure Fingušt Prebil (1989, Ljubljana) \nGraduated from the Academy of Fine Arts and Design under prof. Srečo Dragan (2012). He finished his Master\'s degree at the Universitat für Kunstlerische und Industrielle Gestaltung in Linz, Austria in Interface Cultures under prof. dr. Christi Sommerer (2017).\n'),
	(26, 'Eva Petrič', 'Eva PETRIČ (1983, Kranj)\nDiplomirala na Univerzi Webster na Dunaju, smer psihologija in vizualna umetnost, pod mentorstvom Luciena Clergueja za fotografijo in Martine Corgnati za vizualno umetnost (2005). Magistrirala iz novih medijev na Transart Institute Berlin / Danube University Krems (2010).\n', 'Eva Petrič (1983, Kranj) \nGraduated from the University Webster in Vienna in Psychology and Visual Art under the mentorship of Lucien Clergue in photography and Martine Corgnati for visual art (2005). She got Master\'s degree in new Media at the Transart Institute Berlin / Danube University Krems (2010).');
/*!40000 ALTER TABLE `author` ENABLE KEYS */;

-- Dumping structure for tabela sunt.hibernate_sequence
CREATE TABLE IF NOT EXISTS `hibernate_sequence` (
  `next_val` bigint(20) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.hibernate_sequence: 3 rows
/*!40000 ALTER TABLE `hibernate_sequence` DISABLE KEYS */;
INSERT INTO `hibernate_sequence` (`next_val`) VALUES
	(1),
	(1),
	(1);
/*!40000 ALTER TABLE `hibernate_sequence` ENABLE KEYS */;

-- Dumping structure for tabela sunt.image
CREATE TABLE IF NOT EXISTS `image` (
  `id` bigint(20) NOT NULL,
  `alt` varchar(511) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `path` varchar(255) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_alt` varchar(511) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `video_path` varchar(100) COLLATE utf8_slovenian_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.image: 87 rows
/*!40000 ALTER TABLE `image` DISABLE KEYS */;
INSERT INTO `image` (`id`, `alt`, `path`, `english_alt`, `video_path`) VALUES
	(1, '', '/1_maja_smrekar/_SIPK-8937-manjsa.jpg', '', '/maja_smrekar.mp4'),
	(2, 'Zaslon, na katerem se predvaja video dokument performansa, v kadru sta ležeča obiskovalka in volk. Desno je miza z veliko odprto knjigo, gre za knjigo umetnika. Zadaj na steni je upodobljena človeška figura s pasjo glavo.', '/1_maja_smrekar/_SIPK-8937.jpg', 'A television screen with video document of a perfomance, in the current shot the performer lies on the floor and a wolf walks around her. The artist book is displayed on the table on the right. A human figure with a head of a dog is portrayed on the wall in the background.', '/maja_smrekar.mp4'),
	(3, 'Obiskovalka galerije opazuje podobo, natisnjeno na steni.', '/1_maja_smrekar/_SIPK-8941.jpg', 'A visitor to the gallery is watching the figure printed on the wall.', '/maja_smrekar.mp4'),
	(4, 'Obiskovalka lista knjigo umetnice.', '/1_maja_smrekar/_SIPK-8952.jpg', 'The visitor is browsing through the artist book.', '/maja_smrekar.mp4'),
	(5, '', '/2_marko_glavac/_SIPK-8882-manjsa.jpg', '', '/marko_glavac.mp4'),
	(6, 'Na levi je šest obtesanih drevesnih debel. Označena so z rimskimi števili od ena do šest ter z različnimi barvami. Desno je miza, na kateri je majhen ekran z navodili za interakcijo z instalacijo in šest posodic z izdelki, ki so narejeni iz ekstraktov dreves. V ozadju je video posnetek hoje skozi pragozd.', '/2_marko_glavac/_SIPK-8882.jpg', 'There are six tree trunks on the left. They are numbered with roman numbers from one to six all with different colours. There is a table on the right, on which is a tablet with instructions and six watch glasses with products made of tree extracts. A video of a walk through the rainforest is projected on the wall in the background.', '/marko_glavac.mp4'),
	(7, 'Obiskovalka stoji pri mizi in se dotakne enega izmed drevesnih izdelkov.', '/2_marko_glavac/_SIPK-8885.jpg', 'A visitor is standing next to the table and is touching one of the tree products.', '/marko_glavac.mp4'),
	(8, 'Obiskovalka se sprehaja med drevesnimi debli v smeri puščic iz diagrama na tleh.', '/2_marko_glavac/_SIPK-8894.jpg', 'A visitor is walking between the tree trunks in the direction of the arrows in the diagram on the floor.', '/marko_glavac.mp4'),
	(9, '', '/3_narvika_bovcon_ales_vaupotic/_SIPK-8974-manjsa.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(10, 'Štiri pravokotne visoke vitrine. V vsaki je majhen srebrn kipec. V ozadju je ekran, na katerem je graf, sestavljen iz krogov in črt, ki prikazuje statistiko o slovenskih literarnih avtoricah.', '/3_narvika_bovcon_ales_vaupotic/_SIPK-8974.jpg', 'Four tall rectangular display showcases. There is one small silver statue in each of them. A televison screen is in the background. It is displaying a graph made of circles and lines that represent statistics about Slovenian women writers.', '/Ales_Narvika_popravljen_video.mp4'),
	(11, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9901.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(12, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9909.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(13, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9920.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(14, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9930.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(15, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9935.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(16, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9938.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(17, '', '/3_narvika_bovcon_ales_vaupotic/IMGSIPK-9943.jpg', '', '/Ales_Narvika_popravljen_video.mp4'),
	(18, '', '/4_franc_solina/_SIPK--manjsa.jpg', '', '/franc_solina.mp4'),
	(19, 'Dva lesena vozička, na vsakem je reliefen marmorni kip. Projektor na stojalu projicira bele pikice na desni kip.', '/4_franc_solina/_SIPK-.jpg', 'Two wooden carts. There is a relief marble sculpture on each cart. A projector on a stand projects small dots of white light on the sculpture beneath it.', '/franc_solina.mp4'),
	(20, 'Za desnim kipom stoji obiskovalka. Roke ima iztegnjene nad kip, igra se s projekcijo svetlobe.', '/4_franc_solina/_SIPK-8985.jpg', 'A visitor is standing behind the statue. Her hands are streched above the statue, she is playing with the projection of the light.', '/franc_solina.mp4'),
	(21, '', '/5_matija_jasarov/_SIPK-9073-manjsa.jpg', '', '/matija_jasarov.mp4'),
	(22, 'Dve temni umetni steni, ki ustvarjata vhod v razstavo. Obiskovalka se naslanja na steno in posluša zvok, ki ga stena oddaja.', '/5_matija_jasarov/_SIPK-9073.jpg', 'Two dark artificial walls that create an entrance to the exhibition. A visitor is leaning on a wall and listening to the sound, which comes from the wall.', '/matija_jasarov.mp4'),
	(23, '', '/6_tnm/_SIPK-9015-manjsa.jpg', '', '/tnm_vat.mp4'),
	(24, 'Na sredi instalacije je velik rdeč kip srca. Levo in desno sta televizijska ekrana. Na vsakem je video posnetek človeškega očesa s sledilcem pogleda. V ozadju na platnu je video posnetek ženske, ki stoji med kipoma grškega kurosa in Michelangelovega Davida in ju gleda.', '/6_tnm/_SIPK-9015.jpg', 'There is a big red sculpture of a heart in the middle. Two television screens are positioned left and right. A video of a human eye with eye tracker is playing on both screens. On the projection canvas in the background there is a video of a woman. She is standing in the middle between the statues of a Greek Curos and Michelangelo\'s David and she is watching them.', '/tnm_vat.mp4'),
	(25, 'Sredi instalacije stoji obiskovalka, ki opazuje kip srca, s svojo senco prekriva video posnetek ženske na projekciji.', '/6_tnm/_SIPK-9020.jpg', 'A visitor is standing in the middle of the installation, watching the heart sculpture. She is covering the woman on the projection with her shadow.', '/tnm_vat.mp4'),
	(26, '', '/7_tilen_zbona/_SIPK-8996-manjsa.jpg', '', '/tilen_zbona.mp4'),
	(27, 'Listi papirja visijo s stropa na nitkah. Na listih so upodobljeni različni pravokotni liki, ki delujejo kot markerji. Desno je ekran, na katerem se predvaja slika z videokamere, ki je usmerjena v liste.', '/7_tilen_zbona/_SIPK-8996.jpg', 'Sheets of paper hang on strings that are attached to the ceiling. Different kinds of square shapes are printed on the sheets, which work as markers. There is a screen on the right showing a video from the videocamera, which is directed to the sheets.', '/tilen_zbona.mp4'),
	(28, 'Obiskovalka v roki drži list in pokaže marker kameri. Na ekranu se slika s kamere dopolni z dodatkom geometrijskega telesa v obogateni resničnosti.', '/7_tilen_zbona/_SIPK-8994.jpg', 'A visitor is holding one of the sheets in her hands. She is showing the marker to the camera. Image from the camera is completed with a geometric shape in augmented reality on the screen.', '/tilen_zbona.mp4'),
	(29, '', '/8_peter_ciuha/_SIPK-8863-manjsa.jpg', '', '/peter_ciuha.mp4'),
	(30, 'Zaslon, na katerem so črte različnih barv. Pod njim je klaviatura s pisanimi tipkami. V ozadju je plakat z raznobarvnimi črtami, ki predstavljajo vizualne zapise skladb.', '/8_peter_ciuha/_SIPK-8863.jpg', 'A screen is displaying lines of different colours. There is a keyboard with colourful keys underneath it. In the background, there is a poster with coloured lines that visualize the music scores.', '/peter_ciuha.mp4'),
	(31, 'Obiskovalka igra na klaviaturo, z igranjem se spreminjajo barve na tipkah in barvne črte, ki se izrisujejo na ekranu.', '/8_peter_ciuha/_SIPK-8865.jpg', 'A visitor is playing the keyboard. Colours on keys are changing  and coloured lines appear on the screen while she is playing.', '/peter_ciuha.mp4'),
	(32, '', '/9_miran_kres/_SIPK-8830-manjsa.jpg', '', '/miran_kres.mp4'),
	(33, 'Črna slika, na kateri so majhne modre in rdeče pike. Levo na steni so 3D očala.', '/9_miran_kres/_SIPK-8830.jpg', 'A black painting with small blue and red dots. There are 3D glasses on the wall on the left.', '/miran_kres.mp4'),
	(34, 'Obiskovalka stoji pred sliko in jo opazuje. Na glavi ima 3D očala, skozi katera vidi točke iz slike razporejene v prostoru.', '/9_miran_kres/_SIPK-8835.jpg', 'A visitor is standing in front of the painting and looking at it. She is wearing 3D glasses with which she sees dots from the painting positioned in space.', '/miran_kres.mp4'),
	(35, '', '/10_evelin_stermitz/_SIPK-8691-manjsa.jpg', '', '/evelin_stermitz.mp4'),
	(36, 'Na steni je izobešen zaslon, na katerem se predvaja video posnetek z valovitimi vzorci v različnih odtenkih modre barve.', '/10_evelin_stermitz/_SIPK-8691.jpg', 'On a wall is a screen, on which is a video with corrugated patterns in different shades of blue.', '/evelin_stermitz.mp4'),
	(37, 'Pred ekranom na levi strani stoji obiskovalka, ki nosi slušalke in gleda v ekran.', '/10_evelin_stermitz/_SIPK-8692.jpg', 'In front of the screen on the left hand side a visitor with headphones is standing and looking at the screen.', '/evelin_stermitz.mp4'),
	(38, '', '/11_gorazd_krnc/_SIPK-8821-manjsa.jpg', '', '/gorazd_krnc.mp4'),
	(39, 'Na steni so prilepljeni listi iz atlasa v kvadratu velikosti približno 2*2 metra. Na tej površini so naslikane prepletene podobe vej, listov, sadežev in ženskih portretov ter delov teles. Deli slike manjkajo, slika pa se nadaljuje tudi po tleh. Talni del slike je označen z rdeče-belim opozorilnim trakom.', '/11_gorazd_krnc/_SIPK-8821.jpg', 'On a wall there are glued pages from an atlas in a square sized 2*2 meters. On them are painted interlaced figures of branches, leaves, fruits and women portraits and parts of bodies. Part of the painting is missing, part of it continues on the floor. Around the floor part is a red-white tape.', '/gorazd_krnc.mp4'),
	(40, '', '/12_metka_zupanic/_SIPK-8746-manjsa.jpg', '', '/metka_zupanic.mp4'),
	(41, 'Obiskovalka posluša zvok videa na slušalkah in gleda v zaslon.', '/12_metka_zupanic/_SIPK-8746.jpg', 'A visitor is listening of a sound of the video on headphones and looking at the screen.', '/metka_zupanic.mp4'),
	(42, 'Na levi strani zgoraj sta dva okvirja s steklom in kolažem izrezanih črno-belih fotografij vojakov, lune in eksplozije. Na desni strani je zaslon, na katerem je video posnetek metka, ki obešen na vrvi niha. Pod zaslonom je na steni napis "There is no terror in the bang, only in the anticipation of it" - "Groza ni pok pištole, ampak čakanje nanj". ', '/12_metka_zupanic/_SIPK-8747.jpg', 'On the upper left side on a wall two pictures with glass frame and collage of black and white photographies of soldiers, moon and explosion are placed. On the right hand side is a screen with a video of a swinging bullet on a rope. Underneath the screen on the wall is a sign: "There is no terror in the bang, only in the anticipation of it". A visitor is listening to a sound of the video on headphones.', '/metka_zupanic.mp4'),
	(43, '', '/13_artur_felicijan_andraz_sedmak/_SIPK-8688-manjsa.jpg', '', '/felicijan_sedmak.mp4'),
	(44, 'Obiskovalka gleda ekrana z obema videema hkrati in na slušalkah posluša zgodbo o zakulisju ne v celoti uspešne gradnje Stožic.', '/13_artur_felicijan_andraz_sedmak/_SIPK-8688.jpg', 'A visitor is watching both screens simultaneously and listening a behind the scenes story of not completely succesful construction of Stožice project.', '/felicijan_sedmak.mp4'),
	(45, 'Na steni sive barve sta obešena dva zaslona. Na levem je video, ki prikazuje opuščeno gradbišče Stožic. Na desnem je video, ki prikazuje navijače med tekmo.', '/13_artur_felicijan_andraz_sedmak/_SIPK-8683.jpg', 'On a grey wall 2 screens are hanged, on which there are videos of abandoned construction site of Stožice and fans during a match.', '/felicijan_sedmak.mp4'),
	(46, '', '/14_robert_cernelc/_SIPK-8853-manjsa.jpg', '', '/robert_cernelc.mp4'),
	(47, 'Na steno je hkrati projiciranih več v mrežo razporejenih kadrov iz črno-belega filma Rop vlaka. Kadri se izmenujejo. V ospredju na klopi sedi obiskovalka in gleda projekcijo. ', '/14_robert_cernelc/_SIPK-8853.jpg', 'In the background on a wall projections of 6 screens arranged in a net with cadres from black and white movie Train robbery are shown. In the foreground a visitor is sitting on a bench and looking towards projection.', '/robert_cernelc.mp4'),
	(48, 'Trenutno se na projekciji predvaja portretni plan moškega z brki in klobukom, ki v rokah drži navzgor usmerjen revolver.', '/14_robert_cernelc/_SIPK-8854.jpg', 'In the background there currently a portrait of a man with mustache and a hat with a gun in his hand is played on the projection.', '/robert_cernelc.mp4'),
	(49, '', '/15_dominik_krizan_olmiah/_SIPK-8810-manjsa.jpg', '', '/dominik_krizan.mp4'),
	(50, 'Na steni je izobešena velika slika s črnim okvirjem, ki je razdeljena na 15 podslik, na katerih so na beli podlagi v črni barvi narisane podobe obraza, oči, vrat in okna. Na tleh pod sliko je mali starinski televizor, na njem se predvaja video branjem iz Marxovega Kapitala. Obiskovalka si ogleduje sliko in video. ', '/15_dominik_krizan_olmiah/_SIPK-8810.jpg', 'On a wall a big painting with black frame divided into 15 subpaintings on which there are black silhouettes of a face, eyes, doors and window is hanged. In front of the painting a visitor is standing and  on the ground there is a small classic TV with a video of a reading from Marx\'s Capital.', '/dominik_krizan.mp4'),
	(51, 'Description is in progress', '/15_dominik_krizan_olmiah/15_krizan_3.jpg', 'Description is in progress', '/dominik_krizan.mp4'),
	(52, 'Description is in progress', '/15_dominik_krizan_olmiah/15_krizan_4.jpg', 'Description is in progress', '/dominik_krizan.mp4'),
	(53, '', '/16_ales_sedmak/_SIPK-8783-manjsa.jpg', '', '/ales_sedmak.mp4'),
	(54, 'Na steni je obešenih 6 slik, po tri na isti višini, na katerih so na beli podlagi črni elementi, ki predstavljajo abstrahirane silhuete gondole, ki se pojavlja v ozadju neke Carpacciove slike. Na malem slikarskem stojalu pod slikami stoji tablica.', '/16_ales_sedmak/_SIPK-8783.jpg', 'On a wall there are 6 paintings, three at the same height, on which there are black elements on a white background that represent abstracted silhouettes of a lift that appears in the background of a Carpaccio\'s painting. On a small painting stand a tablet is placed.', '/ales_sedmak.mp4'),
	(55, 'Pred slikami je obiskovalka, ki si na tablici ogleduje zapis koncepta projekta. Pod slikami je ekran, nakaterem je pojasnilo koncepta projekta.', '/16_ales_sedmak/_SIPK-8787.jpg', 'In front of the 6 paintings is a visitor who is looking at the screen and reading about the concept of the project.', '/ales_sedmak.mp4'),
	(56, '', '/17_crtomir_frelih/_SIPK-9032-manjsa.jpg', '', '/crtomir_frelih.mp4'),
	(57, 'Na steni so fotografije ljudi, ki v rokah držijo paket. Spodaj levo je miza, na kateri so škatle bele in rumene barve, na tleh pod in zraven mize pa je še več škatel, ki niso pobarvane.', '/17_crtomir_frelih/_SIPK-9032.jpg', 'On a wall there are photographies of people holding packages in their hands. On the bottom left is a table with white and yellow boxes on it. On the ground below and next to the table there are more carton boxes.', '/crtomir_frelih.mp4'),
	(58, 'V ospredju je umetnik, v rokah drži rumeno škatlo, ki je opremljena s poštnim naslovom. Za njim je miza z grafičnimi pripomočki, na kateri umetnik kot performer v galeriji odtiskuje podobe črnih in belih lisic na škatle. V ozadju na steni so natisnjeni sebki ljudi, ki so po pošti prejeli škatle.', '/17_crtomir_frelih/_SIPK-8918.jpg', 'In the foreground there is an artist who is holding a bigger yellow package with postal address in his hands. Behind him is a table with graphic accessories, on which  the artist as the performer in the gallery prints figures of white and black foxes on the boxes. In the background on the wall seflies of people that received the packages by mail are printed.', '/crtomir_frelih.mp4'),
	(59, '', '/18_dorian_rudolf_spanzel/_SIPK-8797-manjsa.jpg', '', '/dorian_rudolf_spanzel.mp4'),
	(60, 'Na steni so obešene štirje plakati. Na vsakem od njih je QR koda, koordinate in navodila gledalcu naj uporabi mobilni telefon za branje plakata.', '/18_dorian_rudolf_spanzel/_SIPK-8797.jpg', '4 posters are hanged on the wall. On each of those is a QR code, coordinates and instructions for a viewer to use his phone to get more information about the project.', '/dorian_rudolf_spanzel.mp4'),
	(61, 'Na plakatu je portret ameriškega predsednika Benjamina Franklina, ki je delno prekrit z delom ameriške zastave in kemično formulo.', '/18_dorian_rudolf_spanzel/18_spanzel_2.jpg', 'On the poster is a portrait of american president Benjamin Franklin who is partly covered with part of the american flag and a chemical formula.', '/dorian_rudolf_spanzel.mp4'),
	(62, 'Na plakatu je grafika lebdečega bradatega moškega z iztegnjeno roko ter napis "supreme".', '/18_dorian_rudolf_spanzel/18_spanzel_3.jpg', 'On the poster there is graphics of floating bearded old man with stretched hand and a sign "supreme".', '/dorian_rudolf_spanzel.mp4'),
	(63, 'Na plakatu je s črtno risbo izrisan in večkrat ponovljen severni medved. Medvede prekrivajo agresivne poteze modre barve, zgoraj stoji napis "got ice". ', '/18_dorian_rudolf_spanzel/18_spanzel_4.jpg', 'On this poster there are multiple sketches of a polar bear. Bears are covered with aggressive blue colour, on the upper corner is a sign "got ice".', '/dorian_rudolf_spanzel.mp4'),
	(64, 'Na plakatu je oranžen krog z napisom "obey", črtno kodo in drobnim besedilom na temo  robotskega načina obnašanja. Pred krogom stoji preprost humanoidni robot.', '/18_dorian_rudolf_spanzel/18_spanzel_5.jpg', 'On the poster there is an orange circle with a sign "obey", QR code and fine text about robotic way of behaving. Before the circle a simple humanoid robot is standing.', '/dorian_rudolf_spanzel.mp4'),
	(65, '', '/19_dusa_jesih/_SIPK-8844-manjsa.jpg', '', '/dusa_jesih.mp4'),
	(66, 'Instalacija je sestavljena iz velikih, lesenih, premičnih plošč. Povezane so s tečaji in se lahko odpirajo kot vrata. Takoj opazimo močan svetlo-temni kontrast, saj so nekateri deli plošč obarvani belo, drugi črno. Oblike so geometrične in spominjajo na igro Tetris.', '/19_dusa_jesih/_SIPK-8844.jpg', 'The installation is made of large wooden boards, which are connected with hinges and can be opened like doors. The bright-dark contrast can be instantly noticed due to the white and black geometric shapes on the boards that resemble the Tetris game.', '/dusa_jesih.mp4'),
	(67, 'Na levi je črno-bela instalacija, na desni pa obiskovalka, ki gleda v ekran. Predvaja se video, ki prikazuje bele in črne kvadrate.', '/19_dusa_jesih/19_jesih_2.jpg', 'There is a black and white installation on the left. A visitor is on the right. She is looking at the screen showing white and black squares.', '/dusa_jesih.mp4'),
	(68, '', '/20_zoran_srdic_janezic/_SIPK-9045-manjsa.jpg', '', '/zoran_srdic_janezic.mp4'),
	(69, 'Fotografirana je prva soba z razstave, na sliki se vidi 6 projektov. Projekt od Zorana Srdića Janežiča je postavljen v sredino prostora. To so 3 pokončne figure, ki spominjajo na stebre in so sestavljene iz sledečih elementov: spodaj je robot škatlaste oblike s kolesi, na sredini so visoke ravne palice, na vrhu nad kapiteljem pa je svetilki podobna prozorna krogla.', '/20_zoran_srdic_janezic/_SIPK-9045.jpg', 'The photograph shows the first room of the exhibition, 6 projects are captured. The project by Zoran Srdić Janežič is situated in the middle of the room. These are 3 vertical figures that resemble columns and are composed of the following elements: below is a box-like robot with wheels, in the middle there are high straight rods, and on the top there are transparent spherical shapes similar to lamps.', '/zoran_srdic_janezic.mp4'),
	(70, 'Dve obiskovalki stojita ob sredinski stebrasti figuri. Leva oseba gleda navzgor proti svetilki, desna oseba pa navzdol proti robotu. Obiskovalki bosta s svojo prisotnostjo sprožili gibanje na svetlobo občutljivih robotov in s tem pobeg stebrov. ', '/20_zoran_srdic_janezic/_SIPK-9054.jpg', 'Two visitors stand by the central column figure. The person on the left looks up towards the lamp, and the person on the right is facing down towards the robot. The visitors will trigger the movement of the light-sensitive robots with their presence.', '/zoran_srdic_janezic.mp4'),
	(71, '', '/21_peter_marolt/_SIPK-8771-manjsa.jpg', '', '/peter_marolt.mp4'),
	(72, 'Na steni visi uokvirjena pesem. Pod njo je podstavek s knjižicami.', '/21_peter_marolt/_SIPK-8771.jpg', 'On the wall there is a printed poem in a picture frame. Underneath stands a pedestal with booklets.', '/peter_marolt.mp4'),
	(73, 'Na podstavku na levi leži knjižica, ki je ovita v mrežo, iz nje vodi mikro USB kabel. Na sredini je list, na njem piše "prostor za vaš medij in projekcijo". Na desni je druga knjiga velikosti zgoščenke in s sliko zgoščenke na naslovnici. ', '/21_peter_marolt/_SIPK-8780.jpg', 'On the left side of the pedestal lies a booklet wrapped in a net out of which a micro USB cable is set up. In the center there is a paper with words "space for your medium and projection". On the right there is a booklet in the size of a CD-ROM.', '/peter_marolt.mp4'),
	(74, 'Obiskovalka lista knjižico in bere pesmi v njej.', '/21_peter_marolt/_SIPK-8774.jpg', 'The visitor is browsing through the booklet and reading poems. ', '/peter_marolt.mp4'),
	(75, '', '/22_tomaz_furlan/_SIPK-8708-manjsa.jpg', '', '/tomaz_furlan.mp4'),
	(76, 'Na televizijskem ekranu je video posnetek performerja, ki uporablja čudne stroje. Trenutno leži na klopci, na katero so pritrjeni ročaji vesel, ki omogočajo telovadbo kot pri veslanju. ', '/22_tomaz_furlan/_SIPK-8708.jpg', 'The TV screen shows a video of a male performer who is using weird machines. Currently he is lying on a bench to which oars for rowing exercise are attached.', '/tomaz_furlan.mp4'),
	(77, 'Obiskovalka na slušalkah posluša zvok videa, ki se predvaja na ekranu. ', '/22_tomaz_furlan/_SIPK-8693.jpg', 'The visitor is using headphones to listen to the sound of the video she is watching on the screen.', '/tomaz_furlan.mp4'),
	(78, '', '/23_vesna_cadez/_SIPK-8735-manjsa.jpg', '', '/vesna_cadez.mp4'),
	(79, 'Na steni je televizijski ekran, na katerem se predvaja video animacija, sestavljena iz barvnih pravokotnikov, ki tvorijo portret ženske, in črtne risbe modnih dodatkov. Prisotne so pretežno svetle pastelne barve, različni odtenki vijolične, zelene in roza. ', '/23_vesna_cadez/_SIPK-8735.jpg', 'On the wall there is a television screen showing a video animation of coloured rectangles that form a portrait of a woman, and a line drawing of fashion accessories. The image consists of mainly pastel colors, different shades of purple, green, and pink.', '/vesna_cadez.mp4'),
	(80, 'Podoba na ekranu vijuga, občasno jo po delih prekrijejo večje barvne pravokotne ploskve. Levo od ekrana stoji obiskovalka in na slušalkah posluša zvok videa. ', '/23_vesna_cadez/_SIPK-8732.jpg', 'The image on the screen winds and is occasionally partly covered by larger colored rectangular shapes. To the left of the screen stands a visitor listening to the sound of the video with the headset.', '/vesna_cadez.mp4'),
	(81, '', '/24_vanja_mervic/_SIPK-8720-manjsa.jpg', '', '/vanja_mervic.mp4'),
	(82, 'Na ekranu se predvaja video posnetek instalacije v Mestni galeriji Nova Gorica. Tam sta na steni dva ekrana. Na desnem ekranu je video-dokument performansa. V levem okvirju so zamrznjeni barvni pigmenti, razporejeni v obliki navpičnih črt, ki se topijo in puščajo sledi na steni. Na tleh pod ekranoma je vrsta kaktusov. Na desni strani video posnetka je obiskovalec s slušalkami, ki gleda instalacijo in posluša zvok videa.', '/24_vanja_mervic/_SIPK-8720.jpg', 'On a TV screen a video document of an installation in the Nova Gorica City Gallery is played. The installation consists of two small screens on the wall, one with a video-document of a performance and the second a frame with frozen pigments arranged in the form of vertical lines that melt and leave coloured traces on the wall. On the floor below the screen is a series of cacti. On the right side of the clip is a visitor with a headset that watches the installation and listens to the sound of the video.', '/vanja_mervic.mp4'),
	(83, 'Situacija iz Mestne galerije se ponovi na tokratni razstavi. Obiskovalka s slušalkami gleda video-dokument na ekranu.', '/24_vanja_mervic/_SIPK-8738.jpg', 'The situation from the City Gallery is repeated at the current exhibition. A visitor with a headset watches the video document on the screen.', '/vanja_mervic.mp4'),
	(84, '', '/25_jure_fingust_prebil/26_fingust_prebil_1_manjsa.jpg', '', '/jure_fingust_prebil.mp4'),
	(85, 'Na mizi se opazi veliko široko knjigo, ki predstavlja dnevnik. Oseba z svojimi rokami gnete glino na dnevniku.', '/25_jure_fingust_prebil/26_fingust_prebil_1.jpg', 'There is a very large book on the table that represents a diary. The person kneads the clay on the diary with his hands. ', '/jure_fingust_prebil.mp4'),
	(86, '', '/26_eva_petric/27_petric_1_manjsa.jpg', '', '/eva_petric.mp4'),
	(87, 'Na sredini stoji kip, kjer se vidi le spodnjo polovico skulpture Afrodite. Na njo meče senca osebe. ', '/26_eva_petric/27_petric_1.jpg', 'In the middle there is a statue where only the lower half of the sculpture of Aphrodite is seen. Shadow of a person is cast on it.', '/eva_petric.mp4');
/*!40000 ALTER TABLE `image` ENABLE KEYS */;

-- Dumping structure for tabela sunt.project
CREATE TABLE IF NOT EXISTS `project` (
  `id` bigint(20) NOT NULL,
  `description` varchar(255) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_description` varchar(512) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_title` varchar(255) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `order_index` int(11) NOT NULL,
  `title` varchar(255) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `make_year` varchar(15) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `comment` varchar(511) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_comment` varchar(511) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `type` varchar(63) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `english_type` varchar(63) COLLATE utf8_slovenian_ci DEFAULT NULL,
  `theme` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_qjo6p1drb3e0mb662hkr9n6i0` (`order_index`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.project: 26 rows
/*!40000 ALTER TABLE `project` DISABLE KEYS */;
INSERT INTO `project` (`id`, `description`, `english_description`, `english_title`, `order_index`, `title`, `make_year`, `comment`, `english_comment`, `type`, `english_type`, `theme`) VALUES
	(1, 'Njen koncept materialnosti na ravni spreminjanja biostruktur v laboratorijih ali v živem svetu, nam daje orodje za dostopanje do lastne evolucije in nas skozi povezave umetnost-znanost-nezavedno uči kako jo razumeti.', 'Her concept of materiality at the level of changing the biostructures in laboratories or in the living world gives us a tool for accessing our own evolution and through the connections of art-science-unconscious teaches us how to understand it.', 'K-9 topology', 1, 'K-9 topologija', '2015 - 2017', 'Gre za večletni projekt, za katerega je avtorica dobila nagrado iz prešernovega sklada. Projekt je zelo dobro premišljen in kaže na možni razvoj ženske skozi evolucijo preko psa v svobodno bitje. Ženska ima svobodo se odločiti, s kom in s čim bo nadaljevala vrsto človeka. Gre za tipično delo hibridne umetnosti, ki nakazuje sodelovanje z znanostjo.', 'This project received a prize from Prešeren sklad. It indicates the development of a woman into a free being. Woman has a right to choose how to live as the human species in the future. This is a tipical case of hybrid art, which indicates corelation with science.', 'Digitalni print in video', 'Digital print and video', NULL),
	(2, 'Projekt ima status raziskovalno performativne prakse in govori o avtorjevih in tudi gledalčevih sposobnostih, da v galerijski prostor vnaša čutno spoznavno, estetsko in predvsem eksistenčno vsebino.', 'The project has the status of a research-performative practice and speaks about the author\'s as well as the spectator\'s abilities to bring sensually cognitive, aesthetic and especially existential content into the gallery space.', '(pre-)Breath (digi)Integrity', 2, '(pra-)Dih (digi)Neokrnjenost', '2017', 'Marko Glavač je za performativno postavitev tega projekta v galeriji dobil nagrado. Instalacijo postavi tako, da mora gledalec razbirati ne samo estetske postavitve, ampak tudi neko podatkovno eksistenčno zgodbo projekta. ', 'Marko Glavač was awarded for performative layout of this project in the gallery. The author sets the installation in a way that besides decoding aestethic layout, the viewer must also understand an existential data of the project story.', 'Interaktivna instalacija', 'Interactive installation', NULL),
	(3, 'Serija miniaturnih skulptur v obliki odlitkov grafov, ki predstavljajo podatke o avtoricah iz literarne zgodovine, je razstavljena kot zamrznjena kontekstualna perspektiva s težnjo, da se ohrani zanamcem.', 'A series of miniature sculptures in the form of the casts of graphs representing the data on female authors from literary history is exhibited as a frozen contextual perspective with a tendency to be preserved for our descendants.', '3D visualization of literary authors', 3, '3D vizualizacija literarnih avtoric', '2017', 'Avtorja iz podatkovnih informacij o življenju literarnih avtoric Evrope naredita 3D model. Gre za arheološko perspektivo za generacije v prihodnosti - nekdo v prihodnosti lahko iz teh podatkovnih 3D modelov razbere podatke o avtoricah. V ozadju teh modelov je ekran v visoki ločljivosti, ki prikazuje dodatne informacije gledalcu.', 'The authors made a 3D model from information about the life of women literary artists. This is a case of archaeological perspective for future generations. In the future the data about women literary artists can be determined with the help of these 3D data models.', 'Skulptura', 'Sculpture', NULL),
	(4, 'Novomedijski objekt, je interaktivna instalacija, ki procesualno posega v tehnologijo hardvera in softvera ter sproža komunikacijo v realnem prostoru. Ta se z oblikovano površino odziva na računalniško generiran snop svetlobe.', 'A new media object is an interactive installation that processually intervenes in the technology of hardware and software and triggers communication in a real space. With its shaped surface, the latter responds to a computer generated light beam.', 'A Light Well I, II', 4, 'Svetlobni vodnjak', '2015', 'Avtor predstavi povezovanje akademske in znanstvene sfere. Solina v tem projektu projicira svetlobo na instalacijo. Gre za povezovanje akademije in znanstvene sfere - za primer novomedijskega dela, ki vključuje tako strojno kot programsko opremo novih tehnologij.', 'The author represents integration of academic and scientific spheres. This is the case of new era project which includes software and hardware of new technologies.', 'Instalacija', 'Installation', NULL),
	(5, 'Telo obiskovalca se premika skozi tri prostore, ki jih določajo tri različna frekvenčna območja. So podobe časa, ki jih ne ustvarja vizualni jezik, temveč zvočne izkušnje. Udeleženec jo doživi vsakič drugače z vstopom v nov prostor.', 'The visitor\'s body moves through three spaces defined by three different frequency ranges. They are the images of time, not created by visual language, but by sound experience. The participant experiences it differently each time by entering a new space.\n ', 'Enter Sound', 5, 'Enter sound', '2017', '', '', 'Kontekstualna instalacija', 'Contextual installation', NULL),
	(6, 'Black box je podatkovni prostor, kjer se gledalec spremeni v kibernetkega avatarja, ki mapira novomedijsko mesto Trbovlje. Še več, obiskovalec lahko preči med različnimi podatki, umetniškimi sistemi, koncepti in strategijami.', 'Black box is a data space where the spectator transforms into a cyber avatar who maps the new media city of Trbovlje. What is more, the visitor can traverse different data, artistic systems, concepts, and strategies.\n', 'TNM - V.A.T.', 6, 'TNM - V.A.T.', '2017', 'To je video instalacija, ki prikazuje senzor za roženico, ki kaže kaj se dogaja z očesom osebe, ko gleda različni podobi. Postavitev projekta je v originalu imela obliko Black Boxa, vendar so se avtorji prilagodili ideji razstave, za katero je pomemben kontinuiran prehod iz projekta v projekt.', 'This is a video installation which exhibits a sensor of a cornea, which shows what happens with the eye of a person when he is looking at different figures. Original layout was in the shape of black box, but the project was adapted to the idea of entire exhibition and its importance for continuous transition from project to project. ', 'Mešana tehnika', 'Mixed technique', NULL),
	(7, 'Projekt je primer interaktivne video instalacije, v kateri gledalec ustvarja svoje lastne kompozicije in skozi ta proces raziskuje in razvija  parametre   čuta  za mero, barvo in skladen odnos  arhitekturnih teles v prostoru.\n', 'The project is an example of an interactive video installation in which spectators create their own compositions and through this process explore and develop the parameters of the sense for dimension, colour, and a symmetrical relationship between architectural bodies in space.\n', '0.1 Puzzle Contemplation-Augmented Case', 7, '0.1 Puzzle Contemplation-Augmented Case', '2015', 'Gledalec pri tem projektu v realnem času z geometrijskimi telesi dela svojo lastno kompozicijo, s čimer ostri svoj čut za mero, velikost in prostor. Glavna ideja je ta, da za razumevanje umetnosti ni pomembna samo klasična umetnost, ampak tudi novi postopki, ki gledalcu pomagajo dekodirati projekt.', 'In real time, the viewer builds his own composition with the help of geometric shapes, which helps him to enhance his spatial senses. The main idea is that the important part of understanding art of 21. century are not just classic, but also new procedures which help the viewer to decode a project.', 'Prostorska instalacija, videoprojekcija, markerji', 'Spatial installation, videoprojection, markers', NULL),
	(8, 'Interaktivna instalacija poleg informacijske paradigme odpira še sistemsko, saj ne gre samo za uporabo najnovejše tehnologije, ampak izumljanje novih programskih vmesnikov za barvno vizualizacijo glasbe.', 'In addition to the information paradigm, the interactive installation also opens a systemic one, as it is not just about using the latest technology, but about inventing new software interfaces for colour visualization of music.', 'A Living Sound That Has Become a Picture', 8, 'Živi zvok, ki je postala slika', '2017', 'Avtor v tem projektu predstavi zvok skozi barvo. Vsaka tipka na instrumentu ima ločeno barvo, tako da se igrana melodija spremeni v grafični zapis, s čimer gledalec ustvarja barvni zvok.', 'In this project the author represents sound by colour. Every key on the instrument has its own colour, so the melody can be interpreted as a graphic record. In this way the viewer creates a graphic sound.', 'Interaktivna instalacija, grafika', 'Interactive installation, graphics', NULL),
	(9, 'Zidna risba je ustvarjena s točkami v dveh komplementarnih barvah. Gledana skozi preprosta barvna očala za videnje virtualnega prostora, ta risba ustvarja navidezno globino polja brez 3D modelacije.', 'The wall drawing is created with points in two complementary colours. Observed through the simple coloured glasses for viewing the virtual space, this drawing creates a virtual depth of the field without the 3D modelling.\n', 'TC 7', 9, 'TC 7', '2017', 'Avtor želi z uporabo različnih komplementarnih barv vzpostaviti tretjo dimenzijo. Z modro in rdečo barvo gledalec dobi občutek za vse tri dimenzije brez komplicirane uporabe tehnologije.', 'With the use of complementary colours the authors want to establish a third dimension. With blue and red colour the feeling of three dimensional space is achieved without the use of complicated technology.', 'Slika', 'Picture', NULL),
	(10, 'Video loop površina je vizualizirana kot matrica srečevanja črne in bele barve skozi proces nastajanja in minevanja. Gledalec jo občuti /vidi/ kot podobnost in razliko, ne da bi ju pred tem razumsko dojel.', 'The video loop surface is visualized as a matrix of black and white colours meeting each other through the process of arising and passing. The spectator feels/sees it as a similarity and difference, without understanding it beforehand on the rational level.\n', 'Black Blue Abstract', 10, 'Black Blue Abstract', '2014', 'Evelin Stermitz z uporabo modre, bele in črne barve vzpostavi valovanje neke sile, ki spreminja barvo. Človek pri dojemanju tega projekta uživa v spreminjajoči se video podobi, preden sploh ugotovi njegov racionalni pomen.', 'With blue, black and white color Evelin Stermitz establishes waving of a force that changes color. Even before understanding the project rationally, the viewer sees on emotional level.', 'Video', 'Video', NULL),
	(11, 'Prostor ustvarja video projekcija na dvodimenzionalno površino, ki jo prekrivajo poslikave tiskov iz geografskega atlasa. Vse plasti se tematsko povezujejo med sabo in kot celota skupaj ustvarjajo metaforo za ujetost Evrope.', 'The space is created by a video projection on a two-dimensional surface, covered by painted prints from the geographical atlas. All layers are thematically interconnected and together as a whole create a metaphor for the entrapment of Europe.', 'Worth Not Knowing Where Knowing Is / Europa', 11, 'Worth not knowing where Knowing is / Europa', '2017', 'Gorazd Krnc je zelo angažiran v polju umetnosti, ki hkrati želi stopiti tudi v kulturno in politično dogajanje. To se kaže tudi v tem projektu, ki se aktualno navezuje na evropsko še sprejemljivo možnost sobivanja - npr. s prihajajočimi migrantskimi tokovi Evropa glede na dogajanja zadnjih let še ni pripravljena na dobrosrčnost ljudi. ', 'Gorazd Krnc art is strongly tied to political and cultural activity which is also clearly visible in this project. It refers to yet acceptable coexistence of Europeans - e.g. with immigrant crisis Europe is apparently not yet prepared for charity and good nature of its population.', 'Intermedijski preplet slikarstva, grafike in videa', 'Intermedian interlace of painting, graphics and video', NULL),
	(12, 'Fizični in simbolni prostor stene, ki jo zasedajo originalni kolaži, video podoba na tv zaslonu in fotografije govori o militarizirani družbi stalnih napetosti, strahu in sovraštva ter preizkušenih tehnologij nadzora in manipulacije.', 'The physical and symbolic area of the wall, occupied by original collages, video image on the TV screen, and photographs, speaks about a militarized society of constant tensions, fear and hatred, and the already tested technologies of control and manipulation.\n', 'And Here We Are', 12, 'And here we are', '2016 - 2017', 'Metka Zupanič je za to razstavo predstavila originalne kolaže, video in zvok, ki gledalcu pomaga vstopiti v projekt; z barvami ozadja pa je omejila njeno razstavno polje. Tekst govori o družbi strahu, o vojni, nasilju in strahu, ki so vedno bolj prisotni v naši civilizaciji, kar avtorica to lepo poveže še z videom- metek, ki niha.', 'Metka Zupanič has presented the collages, video and sound that helps the spectator to understand her project; background colours are used in order to limit the exhibition edge. The text about society of fear, about war and horror, which are widely present in our civilization is thouthfully linked to a video - a swinging bullet.', 'Fotografija, kolaž, video', 'Photography, collage, video', NULL),
	(13, 'Video instalacija dveh del na dveh ekranih in z dvema diametralno nasprotujočima vsebinama, angažirano govori o moči in manipulaciji medijev, ki smo jo vsi deležni vsak dan, ob vsakem času in vsepovsod.', 'The video installation of two works on two screens and with two diametrically opposite contents in an engaged manner speaks about the power and manipulation by the media, which we are all subjected to every day, every time, and everywhere.\n', 'Arena', 13, 'Arena', '2017', 'Dva različna avtorja predstavita informacije, ki se dogajajo istočasno. Na eni strani dvorana v Stožicah in posnetki, ki smo jih deležni preko televizije kažejo na evforično vzdušje in navdušenje - Stožice so kulturni objekt, kjer lahko gledalec uživa. Po drugi strani pa razpadajoči del objekta, kjer naj bi bile trgovine, propada, je kot neko apokaliptično mesto. Dva ekrana prikazujeta dve različnosti v enem dogodku.', 'The same information is represented in two different perspectives by two different authors. On one hand, the Stožice arena and broadcasted videos shows euphoria and excitement - Stožice are cultural object intended for entertainment. But on the other hand decaying part of the arena where a mall was supposed to be built is like an apocaliptic world, which portrays the exact opposite of previous joyfulness of the same event.', 'Paralelni video', 'Parallel video', NULL),
	(14, 'Gre za video re-montažo filma, ki je prvič v zgodovini filma uporabil naracijo. V konceptu sinhronega predvajanja več zaporednih kadrov avtor ustvarja med prostore, s katerimi omogoča drugačne, nove načine branja pripovedi.', 'This is a video re-editing of the film which used narrative for the first time in history. In the concept of synchronous streaming of several successive frames, the author creates interspaces, which allow for different, new ways of reading the narrative.\n', 'The Great Train Robbery 1903', 14, 'Veliki rop vlak 1903', '2017', 'Avtor jemlje arhivske posnetke velikega ropa vlaka, ki je prvi film, ki v vsebino vnaša naracijo, to je možnost različnega načina branja. Černelč je film razplastil na različne kadre in jih razvrščal v horizontalne nize, gledalcu pa prepustil nalogo dekodiranja. Sivina ozadja omogoča, da človek vse slike dojame v celotnem pogledu - vse slike se navezujejo druga na drugo.', '', 'Video', 'Video', NULL),
	(15, 'S podobami na platnu in povezavo z video sliko performansa, gradi avtor skupno polje razumevanja, ki ne problematizira le koncept vstopa slike v medij, ampak pokaže tudi na spremenjeno vlogo njenega statusa.', 'With the images on the canvas and the connection with a video image of a performance, the author builds a common field of understanding, which does not only problematize the concept of the entry of an image into the medium, but also shows the changed role of its status.', 'Fear, Country', 15, 'Strah, Država', '2017', 'Dominik Križan je v tem projektu video združil s klasično sliko, ki je v maniri filmskih podob ekspresionističnega filma z začetka 20. stoletja. Na njem je podoba akcij presnetih iz filmov, tekst je citiran s Marxove knjige Kapital.', 'Dominik Križan has linked classic image with expresionist style video from the early 20th century. It represents action scenes adapted from movies, text is cited from Marx\'s book Capital.', 'Akril na platnu, Video', 'Acrylic paint on canvas, Video', NULL),
	(16, 'Prostorsko instalacijo gradijo monotipije, art in process ter video listanje po dnevniškem zapisu. Ta je kot ideja in postopek vseskozi prisoten v nastajanju dela. Končno je del celostne umetnine, ki je skupek vseh postopkov ustvarjanja.', 'The spatial installation consists of monotypes, art in process, and video browsing through a diary entry. As an idea and procedure, the latter is always present in the creation of the work. Finally, it is part of the integral artwork, which is an aggregate of all creation processes.', 'Homage to Vittore Carpaccio', 16, 'Hommage a Vittore Carpaccio', '2016 - 2017', 'V tem projektu je Sedmak prestopil iz klasičnega grafičnega dela v postavitev, ki združuje več informacij skupaj z namenom, da bi gledalec vstopil v dekodiranje tega projekta.', 'In this project Sedmak has changed from classic graphic art to a more modern installation that joins together different information in order to decode and interpret the project in a different way.', 'Tuš na papirju', 'Shower on a papir', NULL),
	(17, 'Avtor na duhovit način reinterpretira grafiko kot sled komuniciranja. Na poštno embalažo in situ tiska grafike, ki jo lahko gledalci uporabijo tako, da jo pošljejo sebi ali drugim. S tem se nanjo odtisnejo še vsi zaznamki poštnega prometa.', 'The author in a witty manner reinterprets the graphics as a trace of communication. He prints graphics on the postal packaging in situ, which the spectators can use to send it to themselves or others. In this manner, all postal traffic bookmarks are imprinted on the packaging as well.\n', 'Fox Box', 17, 'Fox box', '2017', 'Avtor je na originalen način vzel podobo, ki se lahko na duhovit način poistoveti s človekom. Gre za primer partizanske grafike; grafika tu pomeni sled odtisa umetnika in odtisa pošte (štampilja, znak pošte itd.). Frelih je tu izkoristil možnost komunikacije z delom, pošiljanjem in distribucijo ter s tem ustvaril dodatno zanimiv objekt.', 'The silhouette of the box can be wittily identified with the viewer. This is an example of partisan graphics; graphic here means a trace of an artist and post office (post stamp, post sign, ...). Frelih has used a possibility of communication with an artistic work, which gives a project additional intrigues. ', 'Stirografija', 'Styrography', NULL),
	(18, 'Avtor nagovarja gledalca v slogu »poparta 21. stoletja«, katerega značilnost je prisvajanje podob iz celotne kulture. Gledalec z uporabo pametnih telefonov in fotografiranja QR kode z razstavljene grafike dostopa do dodatnih informacij.', 'The author addresses the spectator in the style of the “pop art of the 21st century«, the characteristic of which is the appropriation of images from the entire culture. By using smartphones and photographing the QR code from the displayed graphics, the spectator accesses additional information.\n', 'Digital Code in Graphics', 18, 'Digitalna koda v grafiki', '2017', 'Projekt je Pop art 21. stoletja, kjer mladi umetnik vzpostavlja lastne paradigme. Poleg slikovnega gradiva vključuje tudi besedo; to je nov način branja. Gledalec mora poleg gledanja tudi brati, s čimer pride do neke kompleksnejše informacije, ki mu tudi pomaga dekodirati grafiko.', 'The project is an example of 21st century Pop art, where artists establish their own paradigms. Alongside graphic material, text is also included in order to give a reader more complex information and help him to understand graphics better.', 'Mešana tehnika', 'Mixed technique', NULL),
	(19, 'Abstraktno prostorsko sliko, strukturirano z geometrijskimi črno belimi polji avtorica poveže s projicirano video podobo. Ta zaradi svoje hitre menjave polj dodatno problematizira avro slike in njenega statičnega pogleda.', 'The author connects an abstract spatial image, structured with geometric black and white fields, with a projected video image. Due to its rapidly changing fields, this further problematizes the aura of the image and its static view.', 'Modus vivendi', 19, 'Modus vivendi', '2017', 'Avtorica v tem projektu združuje sliko z video podobo in tako problematizira sliko na nivoju objekta, ki se ga da v prostor postaviti na različne načine. Slika skupaj s prostorom predstavlja neko zaokroženo celoto.', 'The author links picture with video image and therefore discusses a picture as an object that can be placed in a room in many different ways in such a way that together they represent a single entity. ', 'Poliptih slika in video animacija', 'Polyptyh and video animation', NULL),
	(20, 'Ko zloži skupaj različne stvari, avtor v novem objektu ugleda stroj ali robota. Temu lahko doda še posebno osvetlitev, ki jo lahko prek ročne brezžične komande spreminja. V to vizijo prepriča tudi gledalca.', 'When folding together a variety of things, the author sees a super robot in the new object. Adding the motion that responds to the degree of light, he also convinces the spectator, who even sees a super-intelligent creature in this self-propelled mammal.\n', 'Epur si muove iluminare', 20, 'Epur si muove iluminare', '2017', 'Avtor se tu igra z imaginacijo - umetnik v kosu železa in železni palici vidi stroj ali robota. Verjetje, ki ga vzpostavi avtor, ko izdela svoj projekt se kot resnica prenese na gledalca, ki ga kot takšnega tudi sprejme.', 'The author here plays with spectator\'s imagination. An artist can imagine a robot or a machine in a piece of iron. This belief that is interpreted by the author when the art is made is then transfered to a viewer who now accepts it as his own.', 'Robotiziran steber', 'Robotized pillar', NULL),
	(21, 'S tremi obče prepoznavnimi predmeti, ki jim daje avtor povsem drug pomen, na humoren način nagovarja gledalca, ter mu tako ponuja razmislek o redefiniranju pomena umetnosti in z njo povezanimi sodobnimi tehnologijami.', 'With three commonly recognizable objects, which the author assigns a completely different meaning, he addresses the spectator in a humorous manner, offering a reflection on the redefinition of the significance of art and related modern technologies.\n', 'Essence, A Book in its infancy - To Care About a New Book', 21, 'Bistvo, Knjiga v povojih', '2017', 'Avtor v tem projektu najnovejšo tehnologijo uporabi na tak način, da jo v bistvu naredi neuporabno v prvotnem smislu. Gledalec mora stvari uporabiti na drugačen način, ki morda ni najbolj očiten in s tem umetnost ugleda z drugega zornega kota.', 'In this project new technology is used in such a way that it becomes useless in its original sense. Her the viewer must use the technology in an unfamiliar way and can now see the installation from different perspective that might not be apparent at first.', 'Konceptualni projekt', 'Conceptual project', NULL),
	(22, 'Projekt obsega poseben video dnevnik, ki ga avtor prikazuje kot dispozitiv vsakodnevnega življenja in delovanja. Pri tem izhaja iz koncepta »show and tell reality« in pomeni vdor realnega v prostor umetnosti.', 'The project includes a special video diary, which the author displays as a slide of everyday life and activity. In doing so, he stems from the concept of »show and tell reality«, which denotes the invasion of real into the field of art.', 'Wear III', 22, 'Wear III', '', 'Tomaž Furlan resničnostne šove iz televizije premakne v umetnost - v svoje domače stanovanje in se nenehno snema. Avtor tako svoje lastno življenje spremeni v reality show, s čimer problematizira vdor realnega sveta v umetnostni.', 'Tomaž Furlan transfers reality show to art, to his own appartement and records himself constantly. The author alters his own life in a reality show to contemplate the idea of invasion of real world to art.', 'Video', 'Video', NULL),
	(23, 'Gre za video generirano podobo, ki je v funkciji stalnega premikanja od praznine do zasedenosti celotne površine ekrana. Nima nobene politične ali vsebinske metafore, lahko pa bi bila uspešna kot podlaga »screen saver« .', 'This is a video-generated image that is in the function of constant movement from the void to the occupancy of the entire surface of the screen. It does not possess any political or content metaphor, but it could be successful as the basis for a »screen saver«.\n', 'Waving', 23, 'Valovanje', '2017', 'Ta projekt obsega video, ki se iz ničesar širi na celoten ekran in daje idejo, da bi se ga dalo uporabiti kot ohranjevalnik zaslona.', 'This project comprises of a video that expands from nothing to the whole screen, which gives an idea that it can be used as a screensaver.', 'Video', 'Video', NULL),
	(24, 'Video dokument posnetih objektov na razstavi, ki se spreminjajo, je obenem stališče in pomenska mreža časa. Beleži jih kamera brez posega avtorja in je brez nepotrebne analize in sinteze.', 'A video document of recorded objects at an exhibition that are changing is at the same time a standpoint and a network of time in terms of meaning. They are recorded by a camera without the author\'s intervention and it is without the unnecessary analysis and synthesis.\n', 'At the begining was a straight line Act 2 - East', 24, 'Na začetku je bila ravna črta - akt 2 vzhod', '2017', 'Barva na monitorju se tali in teče. Forma projekta na ta način problematizira samo grafiko in s tem tudi njeno distrukcijo.', 'Colour on monitor is melting and flowing. The form of this project discusses the graphics and its own distruction.', 'Video', 'Video', NULL),
	(25, 'To je video, ki se navezuje na avtorjevo interaktivno instalacijo My haptic diary. V njej so posnetki interakcije gledalcev in projiciranih posameznih video zapisov akcije gnetenja v glino, ki se konča v nerazpoznavnostii podobe.', 'This is a video that relates to the author\'s interactive installation My Haptic Diary. It consists of the images of the interaction between the spectators and the projected individual videos of kneading clay, which ends in the unrecognizability of the image.\n', 'My Sensory Diary', 25, 'Moj čutni dnevnik', '2016', 'Gre za video posnetkov gledalca in njegovega dejanja gnetenja gline, ki se konča v zgostitvi in nerazpoznavni podobi.', 'This is an interactive installation which shows the tape of a viewer and his kneading of clay which ends in thickening and unrecognizable figure.', 'Video', 'Video', NULL),
	(26, 'Avtorica v svojem video loopu opisuje lasten pogled na znano antično skulpturo Afrodite v enem samem trevelingu. Ta je narejen tako, da sledi objektivu kamere, ta pa očesu kot podaljšku notranjega vida ustvarjalke.', 'In her video loop, the author describes her own view of the famous antique sculpture of Aphrodite. The sight of her in the video follows the camera lens, which follows the eye as an extension of the inner vision of the artist.', 'One Size Fits All', 26, 'One size fits all', '2017', 'Avtorica se s projektom s pomočjo kamere in svoje sence, ki jo meče na skulpturo premika po prostoru, in s tem obravnava nov, drugačen način funkcije, ki jo ima danes video v umetnosti.', 'The author moves around a room with a help of a camera and her own shadows on a sculpture. This is another original function that a video could have in modern art.', 'Video loop', 'Video loop', NULL);
/*!40000 ALTER TABLE `project` ENABLE KEYS */;

-- Dumping structure for tabela sunt.project_author
CREATE TABLE IF NOT EXISTS `project_author` (
  `project_id` bigint(20) NOT NULL,
  `author_id` bigint(20) NOT NULL,
  UNIQUE KEY `UK_a20kceg39il5wnta7fbf5ogjn` (`author_id`),
  KEY `FKtnw80x85ym27vhqlqto2u79a8` (`project_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.project_author: 26 rows
/*!40000 ALTER TABLE `project_author` DISABLE KEYS */;
INSERT INTO `project_author` (`project_id`, `author_id`) VALUES
	(1, 1),
	(2, 2),
	(3, 3),
	(4, 4),
	(5, 5),
	(6, 6),
	(7, 7),
	(8, 8),
	(9, 9),
	(10, 10),
	(11, 11),
	(12, 12),
	(13, 13),
	(14, 14),
	(15, 15),
	(16, 16),
	(17, 17),
	(18, 18),
	(19, 19),
	(20, 20),
	(21, 21),
	(22, 22),
	(23, 23),
	(24, 24),
	(25, 25),
	(26, 26);
/*!40000 ALTER TABLE `project_author` ENABLE KEYS */;

-- Dumping structure for tabela sunt.project_image
CREATE TABLE IF NOT EXISTS `project_image` (
  `project_id` bigint(20) NOT NULL,
  `image_id` bigint(20) NOT NULL,
  PRIMARY KEY (`project_id`,`image_id`),
  UNIQUE KEY `UK_8bkrm4pg8l0oel91mp74j5js9` (`image_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

-- Dumping data for table sunt.project_image: 87 rows
/*!40000 ALTER TABLE `project_image` DISABLE KEYS */;
INSERT INTO `project_image` (`project_id`, `image_id`) VALUES
	(1, 1),
	(1, 2),
	(1, 3),
	(1, 4),
	(2, 5),
	(2, 6),
	(2, 7),
	(2, 8),
	(3, 9),
	(3, 10),
	(3, 11),
	(3, 12),
	(3, 13),
	(3, 14),
	(3, 15),
	(3, 16),
	(3, 17),
	(4, 18),
	(4, 19),
	(4, 20),
	(5, 21),
	(5, 22),
	(6, 23),
	(6, 24),
	(6, 25),
	(7, 26),
	(7, 27),
	(7, 28),
	(8, 29),
	(8, 30),
	(8, 31),
	(9, 32),
	(9, 33),
	(9, 34),
	(10, 35),
	(10, 36),
	(10, 37),
	(11, 38),
	(11, 39),
	(12, 40),
	(12, 41),
	(12, 42),
	(13, 43),
	(13, 44),
	(13, 45),
	(14, 46),
	(14, 47),
	(14, 48),
	(15, 49),
	(15, 50),
	(15, 51),
	(15, 52),
	(16, 53),
	(16, 54),
	(16, 55),
	(17, 56),
	(17, 57),
	(17, 58),
	(18, 59),
	(18, 60),
	(18, 61),
	(18, 62),
	(18, 63),
	(18, 64),
	(19, 65),
	(19, 66),
	(19, 67),
	(20, 68),
	(20, 69),
	(20, 70),
	(21, 71),
	(21, 72),
	(21, 73),
	(21, 74),
	(22, 75),
	(22, 76),
	(22, 77),
	(23, 78),
	(23, 79),
	(23, 80),
	(24, 81),
	(24, 82),
	(24, 83),
	(25, 84),
	(25, 85),
	(26, 86),
	(26, 87);
/*!40000 ALTER TABLE `project_image` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
